name: objectdb_flutter
description: Flutter ObjectDB listener with reactive store
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

  objectdb: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
