name: objectdb_flutter
description: Flutter ObjectDB listener with reactive store
version: 0.0.1
author: Team netz.chat <dev@netzchat.com>
homepage: https://github.com/netz-chat/objectdb_flutter

dependencies:
  flutter:
    sdk: flutter

  objectdb: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
